name: sdc2-tfm
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - astropy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - ipykernel
  - pyyaml
  - tqdm
  - pip:
      - ska-sdc2-scoring-utils
